import React from "react";

const sizeClasses = {
  txtPoppinsLight8: "font-light font-poppins",
  txtPoppinsRegular9Green600: "font-normal font-poppins",
  txtPoppinsSemiBold125: "font-poppins font-semibold",
  txtPoppinsMedium11Gray700: "font-medium font-poppins",
  txtPoppinsLight7: "font-light font-poppins",
  txtPoppinsRegular8Black900b2: "font-normal font-poppins",
  txtPoppinsMedium9: "font-medium font-poppins",
  txtPoppinsLight9: "font-light font-poppins",
  txtPoppinsSemiBold13: "font-poppins font-semibold",
  txtPoppinsRegular125: "font-normal font-poppins",
  txtPoppinsMedium155: "font-medium font-poppins",
  txtPoppinsBold25TealA400: "font-bold font-poppins",
  txtPoppinsSemiBold15: "font-poppins font-semibold",
  txtPoppinsMedium75: "font-medium font-poppins",
  txtPoppinsSemiBold10: "font-poppins font-semibold",
  txtPoppinsLight10WhiteA700: "font-light font-poppins",
  txtPoppinsBold25LightblueA200: "font-bold font-poppins",
  txtPoppinsMedium30: "font-medium font-poppins",
  txtPoppinsSemiBold12: "font-poppins font-semibold",
  txtPoppinsSemiBold18: "font-poppins font-semibold",
  txtPoppinsMedium75Gray700: "font-medium font-poppins",
  txtPoppinsSemiBold85Green600: "font-poppins font-semibold",
  txtPoppinsRegular10Green600: "font-normal font-poppins",
  txtPoppinsRegular18: "font-normal font-poppins",
  txtPoppinsMedium95Gray600: "font-medium font-poppins",
  txtPoppinsRegular15: "font-normal font-poppins",
  txtPoppinsRegular12Black900: "font-normal font-poppins",
  txtPoppinsRegular17: "font-normal font-poppins",
  txtPoppinsMedium30Green600: "font-medium font-poppins",
  txtPoppinsSemiBold125Black900b2: "font-poppins font-semibold",
  txtPoppinsMedium25: "font-medium font-poppins",
  txtPoppinsSemiBold25: "font-poppins font-semibold",
  txtPoppinsMedium125Gray900: "font-medium font-poppins",
  txtPoppinsSemiBold10WhiteA700: "font-poppins font-semibold",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtPoppinsRegular12Gray700: "font-normal font-poppins",
  txtPoppinsSemiBold22: "font-poppins font-semibold",
  txtPoppinsRegular15WhiteA700: "font-normal font-poppins",
  txtPoppinsRegular20: "font-normal font-poppins",
  txtPoppinsRegular10Gray700: "font-normal font-poppins",
  txtPoppinsMedium15Gray700: "font-medium font-poppins",
  txtPoppinsLight15Green600: "font-light font-poppins",
  txtPoppinsMedium15Gray900: "font-medium font-poppins",
  txtPoppinsRegular115: "font-normal font-poppins",
  txtPoppinsLight15: "font-light font-poppins",
  txtPoppinsSemiBold13Black90066: "font-poppins font-semibold",
  txtPoppinsBold15: "font-bold font-poppins",
  txtPoppinsMedium20Gray700: "font-medium font-poppins",
  txtPoppinsLight13: "font-light font-poppins",
  txtPoppinsMedium15WhiteA700: "font-medium font-poppins",
  txtPoppinsLight95: "font-light font-poppins",
  txtPoppinsMedium125: "font-medium font-poppins",
  txtPoppinsLight10: "font-light font-poppins",
  txtPoppinsMedium12WhiteA700: "font-medium font-poppins",
  txtPoppinsSemiBold18WhiteA700: "font-poppins font-semibold",
  txtPoppinsRegular10: "font-normal font-poppins",
  txtPoppinsMedium13: "font-medium font-poppins",
  txtPoppinsMedium11: "font-medium font-poppins",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtPoppinsLight9Black90099: "font-light font-poppins",
  txtPoppinsMedium12: "font-medium font-poppins",
  txtPoppinsMedium10: "font-medium font-poppins",
  txtPoppinsMedium95: "font-medium font-poppins",
  txtPoppinsRegular10Black90066: "font-normal font-poppins",
  txtPoppinsSemiBold155: "font-poppins font-semibold",
  txtPoppinsMedium15: "font-medium font-poppins",
  txtPoppinsSemiBold85WhiteA700: "font-poppins font-semibold",
  txtPoppinsMedium12Black900: "font-medium font-poppins",
  txtPoppinsMedium12Green600: "font-medium font-poppins",
  txtPoppinsBold25YellowA400: "font-bold font-poppins",
  txtPoppinsMedium15RedA700: "font-medium font-poppins",
  txtPoppinsRegular125Black9008c: "font-normal font-poppins",
  txtPoppinsSemiBold85: "font-poppins font-semibold",
  txtPoppinsRegular125Black90099: "font-normal font-poppins",
  txtPoppinsBold25: "font-bold font-poppins",
  txtPoppinsRegular8WhiteA700: "font-normal font-poppins",
  txtPoppinsRegular135: "font-normal font-poppins",
  txtPoppinsRegular9: "font-normal font-poppins",
  txtPoppinsRegular8: "font-normal font-poppins",
  txtPoppinsLight9WhiteA700: "font-light font-poppins",
  txtPoppinsMedium25Gray700: "font-medium font-poppins",
  txtPoppinsRegular7: "font-normal font-poppins",
  txtPoppinsRegular15Gray700: "font-normal font-poppins",
  txtPoppinsRegular17Gray700: "font-normal font-poppins",
  txtPoppinsLight4: "font-light font-poppins",
  txtPoppinsMedium12Gray700: "font-medium font-poppins",
  txtPoppinsLight95Teal900: "font-light font-poppins",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
